### ISSUE TITLE
Using this setup for live tv ?

### ISSUE THREAD

**Issue by scramatte** [phamvinhthanh/cdn-streaming#1]
Do this setup  can be used for live tv ? 
I mean If  I'got  a live tv channel  and If  people are watching same tv channel do I will save bandwith ?

**Comment by phamvinhthanh** [comment]
Hi Scramatte,

yes, you can setup for live tv. If you setup as diagram: Origin Server ---> Edge Server (Caching CDN) --> Users, you will save bandwidth from Origin to Edge.
